### PR TITLE
Feature/regexp replacement

### PR DESCRIPTION
**Pull request by Rexios80**
Added the ability to specify a string to replace matched words

### CODE REVIEW

**Comment by jWinterDay** [comment]
@Rexios80  perfect! will merge it next week

**Comment by Rexios80** [comment]
Cool! We might want to merge my other pull request first and then update this one to match.

**Comment by jWinterDay** [comment]
@Rexios80 hello! I merged another MR and now there are some conflicts

**Comment by Rexios80** [comment]
Yeah I figured. I'll fix them.

**Comment by Rexios80** [comment]
You will probably want to test that first

**Comment by Rexios80** [comment]
Well tests fail but they're failing on master too so not sure if fixing them is within the scope of this PR

**Comment by jWinterDay** [comment]
ok, merged

**Pull request merged**
